# Generated by Django 3.0.3 on 2021-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('contents', models.CharField(max_length=300, null=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('Dürümler', 'Dürümler'), ('Patates & Tavuk & Sos', 'Patates & Tavuk & Sos'), ('Makarnalar', 'Makarnalar'), ('Tatlılar', 'Tatlılar'), ('İçecekler', 'İçecekler')], default='Pizzalar', max_length=200)),
            ],
        ),
    ]
