# Generated by Django 3.0.3 on 2021-06-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='category',
            field=models.CharField(choices=[('Dürümler', 'Dürümler'), ('Atıştırmalık & Sos', 'Atıştırmalık & Sos'), ('Makarnalar', 'Makarnalar'), ('Tatlılar', 'Tatlılar'), ('İçecekler', 'İçecekler')], default='Pizzalar', max_length=200),
        ),
    ]
