# Generated by Django 3.0.3 on 2021-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_auto_20210624_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
