# Generated by Django 3.0.3 on 2021-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_pizza_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='gain',
            field=models.FloatField(null=True),
        ),
    ]
