# Generated by Django 3.0.3 on 2021-06-16 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210616_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='gain',
        ),
    ]
