# Generated by Django 3.0.3 on 2021-06-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_pizza_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='gain',
        ),
    ]
