# Generated by Django 3.0.3 on 2021-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_remove_pizza_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=models.CharField(choices=[('Cazip Pizzalar', 'Cazip Pizzalar'), ('Özel Pizzalar', 'Özel Pizzalar'), ('Bol Malzemeli Pizzalar', 'Bol Malzemeli Pizzalar'), ('Gurme Pizzalar', 'Gurme Pizzalar')], default='Cazip Pizzalar', max_length=200),
        ),
    ]
