# Generated by Django 3.0.3 on 2021-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_productsratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='forRating',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
