# Generated by Django 3.0.3 on 2021-06-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0012_auto_20210626_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryManagment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='salesCount',
            field=models.IntegerField(default=0),
        ),
    ]
