# Generated by Django 3.0.3 on 2021-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0013_auto_20210627_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymanagment',
            name='kind',
            field=models.CharField(choices=[('Pizza', 'Pizza'), ('Kampanya', 'Kampanya'), ('Ekstra', 'Ekstra')], default='Pizza', max_length=200),
        ),
    ]
