# Generated by Django 3.0.3 on 2021-06-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizzas', '0015_auto_20210628_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsratings',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza'),
        ),
        migrations.AddField(
            model_name='productsratings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
