# Generated by Django 3.0.3 on 2021-06-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0016_auto_20210629_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsratings',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='productsratings',
            name='userId',
        ),
    ]
