# Generated by Django 3.0.3 on 2021-06-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tempuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
