# Generated by Django 3.0.3 on 2021-06-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210624_1158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
