# Generated by Django 3.0.3 on 2021-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaId', models.IntegerField()),
                ('piece', models.IntegerField(default=1)),
                ('size', models.CharField(choices=[('1', 'Küçük Boy'), ('2', 'Orta Boy'), ('3', 'Büyük Boy')], default='Orta Boy', max_length=100)),
            ],
        ),
    ]
