# Generated by Django 3.0.3 on 2021-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('pizzasIds', models.CharField(max_length=150)),
                ('size', models.CharField(max_length=200)),
                ('piece', models.CharField(max_length=200)),
                ('sum_price', models.IntegerField()),
                ('adress', models.TextField(max_length=300)),
                ('phone_number', models.CharField(max_length=11)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='basketitem',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
