# Generated by Django 3.0.3 on 2021-06-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210613_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpizza',
            options={'ordering': ['-basketId']},
        ),
    ]
