# Generated by Django 3.0.3 on 2021-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_auto_20210613_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizza',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
