# Generated by Django 3.0.3 on 2021-06-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_auto_20210613_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='payment_method',
            field=models.CharField(max_length=200),
        ),
    ]
