# Generated by Django 3.0.3 on 2021-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_auto_20210613_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='created_date',
            field=models.DateTimeField(default='2021-06-16 16:23'),
        ),
    ]
