# Generated by Django 3.0.3 on 2021-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20210616_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
