# Generated by Django 3.0.3 on 2021-06-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20210616_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='sum_price',
            field=models.FloatField(),
        ),
    ]
