# Generated by Django 3.0.3 on 2021-06-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_auto_20210617_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpizza',
            name='user_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
